development:
  adapter: async

test:
  adapter: test

production: &production
  url: <%= ENV.fetch("PRODUCTION_REDIS_URL") %>
  :url:  redis://redistogo:328xxxxxxxxxxxxxd2@dory.redistogo.com:11403/
  :host: spinyfin.redistogo.com
  :port: 9521
  :inline: true
  :timeout: 1
