development:
  adapter: async

test:
  adapter: test

production: &production
  :url:  redis://redistogo:720d4180e6e2bd2835cdc947ef0b305a@spinyfin.redistogo.com:9521/
  :host: spinyfin.redistogo.com
  :port: 9521
  :inline: true
  :timeout: 1
