default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['PRIMARY_DB_USERNAME'] %>
  password: <%= ENV['PRIMARY_DB_PASSWORD'] %>
  database: <%= ENV['PRIMARY_DB_NAME'] %>
  host: <%= ENV['PRIMARY_DB_HOST'] %>
  port: <%= ENV['PRIMARY_DB_PORT'] %>

development:
  <<: *default
  database: shorten_url_dev

test:
  <<: *default
  database: shorten_url_test

production:
  <<: *default
  database: shorten_url_pro
